#!/usr/bin/env python3
"""
Step 11: Validate paper claims, check numerical assertions, and generate LaTeX macros.
Exports results/paper_b_generated_metrics.tex.
"""

from pathlib import Path
import json
import pandas as pd

PROCESSED_DIR = Path("/home/sengar/sustainable-edge-quality-intelligence/results/processed")
RAW_RESULTS_DIR = Path("/home/sengar/sustainable-edge-quality-intelligence/results/raw")
RESULTS_DIR = Path("/home/sengar/sustainable-edge-quality-intelligence/results")


def main():
    print("=== Step 11: Validating Paper Claims and Generating Macros ===")

    # 1. Load evaluations
    df_eval = pd.read_csv(PROCESSED_DIR / "scenario_evaluations.csv")

    # 2. Load energy summary
    with open(RAW_RESULTS_DIR / "energy_summary.json") as f:
        energy_data = json.load(f)

    # 3. Load break-even table
    df_be = pd.read_csv(PROCESSED_DIR / "break_even_table.csv")

    # 4. Load Monte Carlo summary
    with open(PROCESSED_DIR / "monte_carlo_summary.json") as f:
        mc_data = json.load(f)

    # Assertions
    # (a) Workload overload: Baseline rho >= 1.0, B4 rho < 0.50 across all scenarios
    for sc in ["precision_component", "machined_metal", "high_value_component"]:
        sub = df_eval[df_eval["scenario"] == sc]
        b0_rho = sub[sub["policy"] == "B0_Raw"]["queue_rho"].values[0]
        b4_rho = sub[sub["policy"] == "B4_Full_Cascade"]["queue_rho"].values[0]
        assert b0_rho >= 1.0, f"Expected B0 to be overloaded (rho >= 1), got {b0_rho}"
        assert b4_rho < 0.50, f"Expected B4 queue to be sustainable (rho < 0.50), got {b4_rho}"

    # (b) Energy measurement: active GPU power is positive
    for stage, m in energy_data["stages"].items():
        if stage != "BASELINE_IDLE":
            assert m["p_active_mean_w"] > 0.0, f"Stage {stage} active power must be > 0"

    # (c) High value component has substantial carbon benefit under B4
    hval_b4_c = df_eval[(df_eval["scenario"] == "high_value_component") & (df_eval["policy"] == "B4_Full_Cascade")]["delta_c_kgco2e"].values[0]
    assert hval_b4_c > 300.0, f"Expected High Value B4 delta C > 300 kgCO2e, got {hval_b4_c}"

    print("All empirical assertions verified successfully.")

    # Extract metrics for LaTeX macros
    p_idle = energy_data["stages"]["BASELINE_IDLE"]["p_total_mean_w"]
    p_full_active = energy_data["stages"]["STAGE_FULL_PIPELINE"]["p_active_mean_w"]
    e_frame_wh = energy_data["stages"]["STAGE_FULL_PIPELINE"]["e_frame_wh"]
    fps_model = energy_data["stages"]["STAGE_MODEL_INFER"]["fps"]

    b4_prec = df_eval[(df_eval["scenario"] == "precision_component") & (df_eval["policy"] == "B4_Full_Cascade")].iloc[0]
    b4_metal = df_eval[(df_eval["scenario"] == "machined_metal") & (df_eval["policy"] == "B4_Full_Cascade")].iloc[0]
    b4_hval = df_eval[(df_eval["scenario"] == "high_value_component") & (df_eval["policy"] == "B4_Full_Cascade")].iloc[0]

    tex_macros = [
        "% Auto-generated empirical macros for Paper B.",
        "% Generated by scripts/11_validate_paper_claims.py - DO NOT EDIT MANUALLY.",
        f"\\providecommand{{\\MeasuredGpuIdlePower}}{{{p_idle:.2f}\\,W}}",
        f"\\providecommand{{\\MeasuredGpuActivePipelinePower}}{{{p_full_active:.2f}\\,W}}",
        f"\\providecommand{{\\MeasuredFrameEnergyWh}}{{{e_frame_wh*1e3:.4f}\\,mWh}}",
        f"\\providecommand{{\\MeasuredInferenceFPS}}{{{fps_model:.1f}\\,FPS}}",
        f"\\providecommand{{\\PrecisionDeltaCarbon}}{{{b4_prec['delta_c_kgco2e']:+.2f}\\,kgCO_2e}}",
        f"\\providecommand{{\\MachinedMetalDeltaCarbon}}{{{b4_metal['delta_c_kgco2e']:+.2f}\\,kgCO_2e}}",
        f"\\providecommand{{\\HighValueDeltaCarbon}}{{{b4_hval['delta_c_kgco2e']:+.2f}\\,kgCO_2e}}",
        f"\\providecommand{{\\PrecisionSQIBalanced}}{{{b4_prec['sqi_balanced']:+.3f}}}",
        f"\\providecommand{{\\MachinedMetalSQIBalanced}}{{{b4_metal['sqi_balanced']:+.3f}}}",
        f"\\providecommand{{\\HighValueSQIBalanced}}{{{b4_hval['sqi_balanced']:+.3f}}}",
        f"\\providecommand{{\\BaselineQueueUtilization}}{{{b0_rho:.2f}}}",
        f"\\providecommand{{\\CascadeQueueUtilization}}{{{b4_rho:.2f}}}",
        f"\\providecommand{{\\MonteCarloDraws}}{{10{{,}}000}}",
    ]

    out_tex = RESULTS_DIR / "paper_b_generated_metrics.tex"
    out_tex.write_text("\n".join(tex_macros) + "\n", encoding="utf-8")
    print(f"Exported verified macros to {out_tex}")
    print("Step 11 completed successfully.\n")


if __name__ == "__main__":
    main()